/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    CastCarousel: typeof import('./src/components/CastCarousel.vue')['default']
    CastCell: typeof import('./src/components/CastCell.vue')['default']
    MediaCarousel: typeof import('./src/components/MediaCarousel.vue')['default']
    MediaCell: typeof import('./src/components/MediaCell.vue')['default']
    MediaHeader: typeof import('./src/components/MediaHeader.vue')['default']
    MovieCarousel: typeof import('./src/components/MoviesCarousel.vue')['default']
    MoviesCarousel: typeof import('./src/components/MoviesCarousel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeriesCarousel: typeof import('./src/components/SeriesCarousel.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    UserCarousel: typeof import('./src/components/UserCarousel.vue')['default']
  }
}
