on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        use: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'npm'

      - run: npm ci