name: Linter
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@v2

      - name: npm install
        run: npm ci

      - name: Run linter
      - uses: sibiraj-s/action-eslint@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          eslint-args: --ignore-path=.gitignore --quiet
          annotations: true